name: 'Pixorize Biochemistry Workbook'
size:
  width: '11in'
  height: '8.5in'
pages:
  page:
    layout_table:
      html: 'input/table-of-contents/layout.html'
      css: 'input/table-of-contents/layout.css'
    data: 'input/table-of-contents/data.json' # all data goes to this one page
  page_sequence:
    layout_image:
      html: 'input/image-page-sequence/1-image-color/layout.html'
      css: 'input/image-page-sequence/1-image-color/layout.css'
    layout_notes:
      html: 'input/image-page-sequence/2-image-notes/layout.html'
      css: 'input/image-page-sequence/2-image-notes/layout.css'
    # length of sequence defined by data.json (should be an array)
    # each page can have access to all of data.json, or just the current item in the iterable (i.e. the array)
    # can inject variables from the current item into the layout.html files. var names will be determined by data.json
    data: 'input/image-page-sequence/data.json'
    media: 'input/image-page-sequence/media'